import React, { useEffect, useState } from "react";
import { AlertTriangle, Filter, ArrowRight, ShieldCheck } from "lucide-react";
import { api } from "../services/api";
import { FindingItem } from "../types";
import { StatusBadge } from "../components/StatusBadge";

interface FindingsProps {
  onNavigate: (path: string) => void;
}

export const Findings: React.FC<FindingsProps> = ({ onNavigate }) => {
  const [findings, setFindings] = useState<FindingItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [categoryFilter, setCategoryFilter] = useState("");
  const [statusFilter, setStatusFilter] = useState("");

  useEffect(() => {
    fetchFindings();
  }, [categoryFilter, statusFilter]);

  const fetchFindings = async () => {
    try {
      setLoading(true);
      const data = await api.getFindings(categoryFilter, statusFilter);
      setFindings(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6 animate-fade-in">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-xl font-bold text-slate-900">Protocol & Clinical Findings</h1>
          <p className="text-xs text-slate-500 mt-0.5">
            Deterministic findings generated by evaluating trial data against protocol rules.
          </p>
        </div>

        {/* Filters */}
        <div className="flex items-center space-x-2 text-xs">
          <select
            value={categoryFilter}
            onChange={(e) => setCategoryFilter(e.target.value)}
            className="px-2.5 py-1.5 bg-white border border-slate-200 rounded-lg text-slate-700"
          >
            <option value="">All Categories</option>
            <option value="SAFETY">Safety</option>
            <option value="DATA_QUALITY">Data Quality</option>
            <option value="COMPLIANCE">Compliance</option>
          </select>

          <select
            value={statusFilter}
            onChange={(e) => setStatusFilter(e.target.value)}
            className="px-2.5 py-1.5 bg-white border border-slate-200 rounded-lg text-slate-700"
          >
            <option value="">All Statuses</option>
            <option value="OPEN">Open</option>
            <option value="RESOLVED">Resolved</option>
          </select>
        </div>
      </div>

      {/* Findings Table */}
      <div className="bg-white rounded-xl border border-slate-200 shadow-xs overflow-hidden">
        <table className="w-full text-left text-xs">
          <thead className="bg-slate-50 text-slate-500 font-semibold border-b border-slate-200 uppercase tracking-wider text-[10px]">
            <tr>
              <th className="py-3 px-4">Finding</th>
              <th className="py-3 px-4">Subject / Site</th>
              <th className="py-3 px-4">Category</th>
              <th className="py-3 px-4">Severity</th>
              <th className="py-3 px-4">Status</th>
              <th className="py-3 px-4">Protocol Rule</th>
              <th className="py-3 px-4 text-right">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {loading ? (
              <tr>
                <td colSpan={7} className="py-8 text-center text-slate-400">
                  Loading clinical findings...
                </td>
              </tr>
            ) : findings.length === 0 ? (
              <tr>
                <td colSpan={7} className="py-8 text-center text-slate-400">
                  No findings matching criteria.
                </td>
              </tr>
            ) : (
              findings.map((f) => (
                <tr
                  key={f.id}
                  className="hover:bg-slate-50 transition-colors cursor-pointer group"
                  onClick={() => onNavigate(`/findings/${f.id}`)}
                >
                  <td className="py-3.5 px-4 font-semibold text-slate-900 group-hover:text-blue-700">
                    {f.title}
                  </td>
                  <td className="py-3.5 px-4">
                    <span className="font-mono font-bold text-blue-600">{f.subject_id}</span>
                    <span className="text-slate-400 ml-1.5">({f.site_id})</span>
                  </td>
                  <td className="py-3.5 px-4">
                    <span className="px-2 py-0.5 rounded font-bold text-[10px] uppercase bg-slate-100 text-slate-700">
                      {f.category}
                    </span>
                  </td>
                  <td className="py-3.5 px-4">
                    <StatusBadge status={f.severity} />
                  </td>
                  <td className="py-3.5 px-4">
                    <StatusBadge status={f.status} />
                  </td>
                  <td className="py-3.5 px-4 font-mono text-slate-500">
                    Protocol {f.protocol_rule}
                  </td>
                  <td className="py-3.5 px-4 text-right">
                    <span className="inline-flex items-center text-xs font-semibold text-blue-600 group-hover:translate-x-0.5 transition-transform">
                      Detail <ArrowRight className="w-3.5 h-3.5 ml-1" />
                    </span>
                  </td>
                </tr>
              ))
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
};
